[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

; ---- Build flags ----
build_flags =
    -Wall
    -Wextra
    -O2
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    ; Uncomment for verbose debug
    ; -DDEBUG

monitor_speed = 115200

; ---- Upload ----
; Change COM port to yours
upload_port = COM6
upload_speed = 115200

lib_deps =
    olikraus/U8g2 @ ^2.35.12
    paulstoffregen/Encoder @ ^1.4.2

; Optional script: prints memory usage after build (safe no-op if you remove it)
extra_scripts =
    pre:scripts/check_size.py
