'use strict';
const $=id=>document.getElementById(id),names=['h1','h2','v1','v2'],labels=['X1','X2','Z1','Z2'];
let port=null,reader=null,writer=null,reading=false,rx='',supported=false,seq=0,epoch=0,txTail=Promise.resolve(),lastRx=0,jog=null,jogTimer=null;
let controller={armed:'0',cal:'0',running:'0',paused:'0',pulse:'0',session:null},axes=Array(4).fill(null),draft={zones:[],order:[]};
const requests=new Map(),logLines=[],parameters=new Map();
const reasons={NOT_ARMED_OR_SAFETY:'Управление отключено или активен вход защиты.',ARM_REQUIRES_STOPPED_FRESH_SAFETY:'Нужны остановленные ПЧ, свежие координаты и неактивный вход E-STOP.',JOG_GATES:'Для этого движения нужно подтвердить направления выбранных приводов.',JOG_REQUIRES_STOPPED:'Дождитесь подтверждённого останова приводов.',JOG_FREQUENCY:'Запрошенная частота ниже P6.03 или P0.14. Проверьте настройки ПЧ и выбранную скорость.',JOG_PROFILE_MAX:'Скорость выше максимума в профиле выбранного привода.',CALIBRATION_INPUT_OR_FREQUENCY:'Проверьте скорость, длительность импульса и P6.03/P0.14. Все приводы должны стоять.',CALIBRATION_PREPARE_TIMEOUT:'Не удалось получить стабильные измерения четырёх датчиков для проверки направления.',CALIBRATION_REJECTED:'Проверка направления не началась: смотрите состояние датчиков и журнал.',PROGRAM_SPEED_BELOW_START_OR_LOWER_LIMIT:'Скорость программы или замедления ниже стартовой/нижней частоты ПЧ. Проверьте P6.03, P0.14 и профили скоростей.',VALUE_CHANGED_RELOAD:'Параметр изменился после чтения. Прочитайте его снова.',WRITE_VERIFY_FAILED:'Запись не подтверждена обратным чтением; управление отключено.',WRITE_REQUIRES_STOPPED_ALLOWED_RANGE:'Запись разрешена после останова и только в допустимом диапазоне.',SESSION:'Подключение сброшено. Подключите пульт заново.',EDIT_REQUIRES_IDLE:'Редактирование доступно после остановки.',AUTO_GATES:'Для запуска нужны четыре проверенных направления, свежие координаты и останов.',VFD_HEALTH:'Потеряна связь с ПЧ или обнаружена авария; управление отключено.',ESTOP_STILL_ACTIVE_OR_BUSY:'Вход E-STOP ещё активен или привод занят. Сброс не выполнен.'};
function reason(code){return reasons[code]||code||'Команда отклонена';}
let busy=false,formDirty=false,lastHandshake=0;
const paramDefs=[
 ['P0.02','Источник команд',1,2,2],['P0.03','Источник частоты',1,9,9],['P0.09','Инверсия FWD/REV',1,0,1],
 ['P0.10','Максимальная частота, Гц',100,0,500,false],['P0.14','Нижняя частота, Гц',100,0,50],
 ['P0.17','Разгон 1, с',10,0,6500],['P0.18','Торможение 1, с',10,0,6500],['P0.19','Шкала времени: 0=1 с, 1=0,1 с, 2=0,01 с',1,0,2,false],
 ['P0.22','Разрешение частоты: 1=0,1; 2=0,01',1,1,2,false],['P0.27','Привязка источников',1,0,0],
 ['P4.00','X1: функция',1,0,49,false],['P4.01','X2: функция',1,0,49,false],['P4.02','X3: функция',1,0,49,false],['P4.03','X4: функция',1,0,49,false],['P4.11','Режим клемм',1,0,3,false],['P4.38','Полярность входов',1,0,65535,false],
 ['P6.00','Пуск: 0=прямой, 1=поиск, 2=предвозбуждение',1,0,2],['P6.03','Стартовая частота, Гц',100,0,10],['P6.04','Удержание стартовой частоты, с',10,0,100],['P6.05','Начальный ток, %',1,0,100],['P6.06','Начальное торможение/предвозбуждение, с',10,0,100],['P6.10','Останов: 0=замедление, 1=выбег',1,0,1],['P8.12','Пауза смены направления, с',10,0,3000],['P8.13','Запрет REV',1,0,1],['P8.14','Ниже предела: 0=предел, 1=STOP, 2=нулевая',1,0,2],['P8.18','Защита пуска',1,0,1,false]
];
function kv(line){return Object.fromEntries(line.split(/\s+/).slice(1).map(t=>{const i=t.indexOf('=');return i>0?[t.slice(0,i),t.slice(i+1)]:null}).filter(Boolean));}
function note(text,bad=false){$('notice').textContent=text;$('notice').style.borderColor=bad?'var(--red)':'var(--blue)';}
function log(text,kind='RX'){const line=`[${new Date().toLocaleTimeString('ru-RU',{hour12:false})}] ${kind} ${text}`;logLines.push(line);if(logLines.length>60000)logLines.splice(0,1000);const pre=$('log');pre.textContent=logLines.slice(-1500).join('\n');if($('scrollLog').checked)pre.scrollTop=pre.scrollHeight;}
function integer(value,min,max){const text=String(value);if(!/^-?\d+$/.test(text))throw Error('Требуется целое число');const n=Number(text);if(!Number.isSafeInteger(n)||n<min||n>max)throw Error(`Значение должно быть ${min}…${max}`);return n;}
function number(id,min,max){return integer($(id).value,min,max);}
function connected(){return !!writer&&supported;}
function armed(){return connected()&&controller.armed==='1'&&lastRx&&Date.now()-lastRx<2200;}
function moving(){return !!jog||controller.running==='1'||controller.pulse==='1';}
function maskReady(mask){return (Number(controller.cal)&mask)===mask;}
function resetSession(){epoch++;supported=false;controller={armed:'0',cal:'0',running:'0',paused:'0',pulse:'0',session:null};axes=Array(4).fill(null);parameters.clear();stopJogTimer();jog=null;$('external').checked=false;for(const r of requests.values()){clearTimeout(r.timer);r.reject(Error('Подключение сброшено'));}requests.clear();renderAxes();render();}
function write(cmd,priority=false){
 if(typeof cmd!=='string'||/[\r\n]/.test(cmd))return Promise.reject(Error('Недопустимая команда'));
 if(cmd!=='service info'&&!supported)return Promise.reject(Error('Нужна прошивка Step9K'));
 if(priority)epoch++;const ticket=epoch;
 const work=async()=>{if(ticket!==epoch)throw Error('Команда отменена');if(!writer)throw Error('COM отключён');log(cmd,'TX');await writer.write(new TextEncoder().encode(cmd+'\n'));};
 const promise=txTail.catch(()=>{}).then(work);txTail=promise;return promise;
}
function request(command,response='@WEB_ACK '){
 const id=++seq;return new Promise((resolve,reject)=>{
  const timer=setTimeout(()=>{requests.delete(id);reject(Error('Нет подтверждения команды'));},6000);
  requests.set(id,{resolve,reject,timer,response});write(`${command} @${id}`).catch(e=>{clearTimeout(timer);requests.delete(id);reject(e);});
 });
}
function token(){if(!armed())throw Error('Сначала разрешите управление');return controller.session;}
async function action(fn){if(busy)return;busy=true;render();try{await fn();}catch(e){note(e.message,true);}finally{busy=false;render();}}
async function stop(){stopJogTimer();jog=null;try{await write('web stop',true);}catch(e){note(e.message,true);}controller.armed='0';render();}
function resolveReply(line,v){const r=requests.get(Number(v.id));if(!r||!line.startsWith(r.response)&&!line.startsWith('@WEB_ACK '))return;requests.delete(Number(v.id));clearTimeout(r.timer);if(v.ok==='0')r.reject(Error(reason(v.reason)||`Ошибка ${v.error}`));else r.resolve(v);}
function processLine(line){
 lastRx=Date.now();if(line.startsWith('FW:')){resetSession();if(writer)write('service info').catch(e=>note(e.message,true));}
 if(line.startsWith('@SERVICE_INFO ')){const v=kv(line);supported=v.fw==='v6-system-step9k-web-control'&&v.build==='FIELD'&&v.diagnosticLock==='0'&&v.auto==='1';$('firmware').textContent=`${v.fw||'—'} · ${v.build||'—'}`;if(supported){note('Mega подключена. Прочитайте настройки и разрешите управление для испытаний.');write('web info').catch(e=>note(e.message,true));}else note('Подключённая прошивка не поддерживает этот веб-пульт.',true);}
 else if(line.startsWith('@WEB_STATE ')){const v=kv(line);if(controller.session&&controller.session!==v.session)resetSession();if(v.armed==='0'&&jog){jog.button?.classList.remove('held');jog=null;stopJogTimer();}controller=v;render();}
 else if(line.startsWith('@WEB_AXIS ')){const v=kv(line),i=Number(v.i);axes[i]={...axes[i],...v};renderAxes();const card=document.querySelector(`[data-profile-card="${names[i]}"]`),sensor=document.querySelector(`[data-sensor-card="${names[i]}"]`);if(card&&card.dataset.dirty!=='1'&&!card.contains(document.activeElement))for(const input of card.querySelectorAll('input'))if(v[input.dataset.key]!==undefined)input.value=v[input.dataset.key];if(sensor&&sensor.dataset.dirty!=='1'&&!sensor.contains(document.activeElement)){sensor.querySelector('[data-offset]').value=v.offset;sensor.querySelector('[data-inverse]').checked=v.invert==='1';}}
 else if(line.startsWith('@HE200 ')){const v=kv(line),i=names.indexOf((v.name||'').toLowerCase());if(i>=0){axes[i]={...axes[i],online:v.online,runHz:v.online==='1'&&Number.isFinite(Number(v.run001))?Number(v.run001)/100:undefined,setHz:v.online==='1'&&Number.isFinite(Number(v.set001))?Number(v.set001)/100:undefined,fault:v.fault};renderAxes();}}
 else if(line.startsWith('@WEB_PARAM ')){const v=kv(line);parameters.set(`${v.drive}:${v.key}`,v);renderParameter(v);resolveReply(line,v);}
 else if(line.startsWith('@WEB_ACK ')){const v=kv(line);resolveReply(line,v);if(v.ok==='0')note(reason(v.reason),true);}
 else if(line.startsWith('@WEB_WRITE ')){const v=kv(line);note(`${v.drive.toUpperCase()} ${v.key}: ${v.before} → ${v.after}; ${v.ok==='1'?'запись проверена':'проверка не прошла'}`,v.ok!=='1');}
 else if(line.startsWith('@PROGRAM ')){draft={...draft,...kv(line),zones:[],order:[]};formDirty=false;renderProgramBase();}
 else if(line.startsWith('@ZONE ')){const v=kv(line);draft.zones[Number(v.n)-1]={...v,enabled:v.en,hPct:v.hpct,vPct:v.vpct};renderZones();}
 else if(line.startsWith('@WEB_ORDER ')){draft.order=kv(line).values.split(',').map(Number);if(!formDirty)$('order').value=draft.order.join(' ');}
 else if(line.startsWith('@WEB_DRY ')){draft.drying=kv(line);if(!formDirty){$('dryEnabled').checked=draft.drying.enabled==='1';for(const [id,key] of [['drySeconds','seconds'],['dryStaging','staging'],['dryX1','x1'],['dryX2','x2'],['dryZ1','z1'],['dryZ2','z2']])$(id).value=draft.drying[key];}}
 else if(line.startsWith('@CAL ')){const v=kv(line);$('calResult').textContent=`${v.drive}: ${v.command}; изменение ${v.deltaMm} мм; измерение ${v.measured==='1'?'принято':'не подтверждено'}; оба направления ${v.ready==='1'?'подтверждены':'пока не подтверждены'}; «+» → ${v.plusCommand}`;}
}
async function readLoop(){const decoder=new TextDecoder();try{while(reading&&reader){const {value,done}=await reader.read();if(done)break;if(value){rx+=decoder.decode(value,{stream:true});let idx;while((idx=rx.indexOf('\n'))>=0){const line=rx.slice(0,idx).replace(/\r$/,'');rx=rx.slice(idx+1);log(line);processLine(line);}}}}catch(e){note('Ошибка COM: '+e.message,true);}finally{reading=false;if(port)await disconnect();}}
async function connect(){try{if(!navigator.serial)throw Error('Откройте пульт в Chrome или Edge через локальный сервер');resetSession();rx='';port=await navigator.serial.requestPort();await port.open({baudRate:115200,bufferSize:65536});writer=port.writable.getWriter();reader=port.readable.getReader();reading=true;readLoop();await write('service info');render();}catch(e){note(e.message,true);await disconnect();}}
async function disconnect(){stopJogTimer();jog=null;reading=false;try{if(writer&&supported)await write('web stop',true);}catch{}try{if(reader){await reader.cancel();reader.releaseLock();}}catch{}try{writer?.releaseLock();}catch{}try{await port?.close();}catch{}reader=null;writer=null;port=null;resetSession();render();}
function renderAxes(){names.forEach((name,i)=>{const a=axes[i]||{},card=$('axes').children[i];card.classList.toggle('stale',a.age===undefined||Number(a.age)>1200);card.querySelector('.value').textContent=a.mm??'—';card.querySelector('.state').textContent=`${name.toUpperCase()} · сырое ${a.raw??'—'} · возраст ${a.age??'—'} мс`;card.querySelector('.hz').textContent=`выход ${a.runHz===undefined?'—':a.runHz.toFixed(2)} Гц · задание ${a.setHz===undefined?'—':a.setHz.toFixed(2)} Гц`;card.querySelector('.fault').textContent=a.fault&&a.fault!=='0x0'?'Ошибка '+a.fault:'';const c=$('calCards').children[i];c.querySelector('.result').textContent=maskReady(1<<i)?`Проверено · FWD ${Number(a.fwdSign)>0?'увеличивает':'уменьшает'} расстояние`:'Нужны два измерения';});}
function render(){
 $('connect').disabled=!!port;$('disconnect').disabled=!port;$('stop').disabled=!connected();$('connection').textContent=port?'COM подключён':'Не подключён';
 $('permit').textContent=armed()?'Управление разрешено':'Управление отключено';$('permit').className=armed()?'good':'';$('arm').disabled=!connected()||!controller.session||!$('external').checked||armed()||busy||controller.busBusy==='1';
 $('clearSafety').disabled=!connected()||Number(controller.estop)!==2||busy||moving();
 $('safety').textContent=`Вход E-STOP: ${Number(controller.estop)?'активен / защёлкнут':'OK'} · концевики Mega: ${controller.limitsEnabled==='1'?'включены':'аппаратная цепь'}`;
 document.querySelectorAll('[data-jog]').forEach(b=>b.disabled=!armed()||!maskReady(Number(b.dataset.mask))||busy||controller.running==='1'||controller.pulse==='1');
 document.querySelectorAll('[data-calibrate]').forEach(b=>b.disabled=!armed()||busy||moving());
 for(const id of ['forget','loadProgram','saveProgram','applyProgram','testPlan','readParams','saveSettings'])$(id).disabled=!armed()||busy||moving();
 $('readParams').disabled=!connected()||busy||moving();
 $('refreshProgram').disabled=!connected()||busy;
 $('home').disabled=!armed()||!maskReady(15)||busy||moving();
 for(const id of ['startAuto','startSteps'])$(id).disabled=!armed()||!maskReady(15)||controller.ready!=='1'||busy||moving()||formDirty;
 $('pause').disabled=!armed()||controller.running!=='1'||controller.paused==='1';$('resume').disabled=!armed()||controller.paused!=='1';$('next').disabled=!armed()||controller.running!=='1';
 $('runState').textContent=controller.running==='1'?(controller.paused==='1'?'Пауза':'Выполняется'):controller.error&&controller.error!=='0'?'Ошибка '+controller.error:'Остановлено';
 $('stepDetail').textContent=`${controller.phase||'IDLE'} · зона ${controller.zone||'—'} · шаг ${controller.step||0}/${controller.steps||0} · ожидание ${controller.wait||0} с${controller.waitOperator==='1'?' · требуется действие оператора':''}${controller.dryAlarm==='1'?' · сушка завершена':''}`;
 $('progress').firstElementChild.style.width=(Number(controller.steps)?Math.min(100,Number(controller.step)/Number(controller.steps)*100):0)+'%';
 $('draftStatus').textContent=formDirty?'Форма изменена; примените перед запуском':'';
 document.querySelectorAll('[data-write-param],[data-profile],[data-sensor]').forEach(b=>b.disabled=!armed()||busy||moving());
}
function stopJogTimer(){if(jogTimer)clearInterval(jogTimer);jogTimer=null;}
async function beginJog(b,event){event.preventDefault();if(jog||!armed()||busy)return;try{const pct=number('jogPct',5,80);jog={target:b.dataset.jog,dir:b.dataset.dir,pct,button:b};b.classList.add('held');b.setPointerCapture?.(event.pointerId);await request(`web jog ${token()} ${jog.target} ${jog.dir} ${pct}`);if(!jog)return;jogTimer=setInterval(()=>{if(jog)write(`web jog ${controller.session} ${jog.target} ${jog.dir} ${jog.pct}`).catch(()=>releaseJog());},180);}catch(e){note(e.message,true);releaseJog();}render();}
async function releaseJog(){if(!jog)return;jog.button?.classList.remove('held');jog=null;stopJogTimer();try{await write(`web release ${controller.session}`,true);}catch(e){note(e.message,true);}render();}
function scale(def,drive){if(['P0.17','P0.18'].includes(def[0])){const t=parameters.get(`${drive}:P0.19`);return t?.ok==='1'?({0:1,1:10,2:100})[Number(t.raw)]:null;}if(['P0.10','P0.14','P6.03'].includes(def[0])){const r=parameters.get(`${drive}:P0.22`);return r?.ok==='1'?({1:10,2:100})[Number(r.raw)]:null;}return def[2];}
function renderParameter(v){const def=paramDefs.find(d=>d[0]===v.key),cell=document.querySelector(`[data-param="${v.key}"][data-drive="${v.drive}"]`);if(!cell||!def)return;const divisor=scale(def,v.drive);cell.querySelector('input').value=v.ok==='1'&&divisor?Number(v.raw)/divisor:'';cell.querySelector('.raw').textContent=v.ok==='1'?`raw ${v.raw}`:`Ошибка ${v.error}; ex ${v.exception}`;cell.querySelector('input').disabled=def[5]===false||!divisor;const btn=cell.querySelector('button');if(btn)btn.disabled=!armed()||busy||moving()||!divisor;}
async function readParameters(){let n=0;const defs=[...paramDefs].sort((a,b)=>['P0.19','P0.22'].includes(a[0])?-1:['P0.19','P0.22'].includes(b[0])?1:0);for(const def of defs)for(const drive of names){$('paramProgress').textContent=`Чтение ${++n}/${defs.length*4}`;try{await request(`web read ${drive} ${def[0]}`,'@WEB_PARAM ');}catch(e){note(`${drive} ${def[0]}: ${e.message}`,true);}}$('paramProgress').textContent='Чтение завершено';for(const v of parameters.values())renderParameter(v);}
async function writeParameter(button){const cell=button.closest('[data-param]'),key=cell.dataset.param,drive=cell.dataset.drive,def=paramDefs.find(d=>d[0]===key),before=parameters.get(`${drive}:${key}`),divisor=scale(def,drive);if(before?.ok!=='1'||!divisor)throw Error('Сначала прочитайте параметр и его шкалу');const text=cell.querySelector('input').value.trim(),value=Number(text);if(!/^\d+(\.\d+)?$/.test(text)||!Number.isFinite(value)||value<def[3]||value>def[4]||Math.abs(value*divisor-Math.round(value*divisor))>1e-7)throw Error('Значение вне диапазона или не соответствует шагу');await request(`web write ${token()} ${drive} ${key} ${before.raw} ${Math.round(value*divisor)}`);await request(`web read ${drive} ${key}`,'@WEB_PARAM ');}
function renderProgramBase(){const d=draft;for(const [id,key] of [['home1','home1'],['home2','home2'],['travel1','travel1'],['travel2','travel2'],['drip','drip'],['tiltPct','tiltPct'],['lowSide','lowSide']])if(d[key]!==undefined)$(id).value=d[key];if(d.slot)$('slot').value=d.slot;if(d.drying){$('dryEnabled').checked=Number(d.drying.enabled)===1;for(const [id,key] of [['drySeconds','seconds'],['dryStaging','staging'],['dryX1','x1'],['dryX2','x2'],['dryZ1','z1'],['dryZ2','z2']])if(d.drying[key]!==undefined)$(id).value=d.drying[key];}}
function renderZones(){const body=$('zones');body.replaceChildren();draft.zones.forEach((z,i)=>{if(!z)return;const row=document.createElement('tr');row.dataset.zone=i;const keys=['enabled','x1','x2','z1','z2','dip','tilt','wait','hPct','vPct'];row.innerHTML=`<td>${i+1}</td>`+keys.map(k=>`<td><input data-key="${k}" type="${k==='enabled'?'checkbox':'number'}" ${k==='enabled'?(z.enabled==='1'||z.enabled===1?'checked':''):`value="${Number(z[k]??(k.endsWith('Pct')?10:0))}"`} min="0" max="${k.endsWith('Pct')?80:k==='dip'||k==='wait'?36000:10000}"></td>`).join('')+`<td><button data-zone-capture="x">X</button><button data-zone-capture="z">Z</button></td>`;body.appendChild(row);row.querySelectorAll('input').forEach(input=>input.addEventListener('change',dirty));row.querySelectorAll('[data-zone-capture]').forEach(b=>b.addEventListener('click',()=>{const side=b.dataset.zoneCapture;const first=side==='x'?0:2;if(!axes[first]||!axes[first+1]||Number(axes[first].age)>1200||Number(axes[first+1].age)>1200){note('Нужны свежие координаты',true);return;}row.querySelector(`[data-key="${side}1"]`).value=axes[first].mm;row.querySelector(`[data-key="${side}2"]`).value=axes[first+1].mm;dirty();}));});if(!formDirty)$('order').value=(draft.order?.length===draft.zones.length?draft.order:draft.zones.map((_,i)=>i+1)).join(' ');render();}
function dirty(){formDirty=true;render();}
function collectProgram(){const zones=[...$('zones').children].map((row,i)=>{const z={n:i+1};for(const input of row.querySelectorAll('input'))z[input.dataset.key]=input.type==='checkbox'?+input.checked:integer(input.value,0,input.dataset.key.endsWith('Pct')?80:input.dataset.key==='dip'||input.dataset.key==='wait'?36000:input.dataset.key==='tilt'?5000:10000);if(z.hPct<5||z.vPct<5)throw Error('Скорости зон: 5…80%');return z;});const order=$('order').value.trim().split(/\s+/).map(x=>integer(x,1,zones.length));if(order.length!==zones.length||new Set(order).size!==zones.length)throw Error('Порядок должен содержать каждую зону ровно один раз');return {home1:number('home1',0,10000),home2:number('home2',0,10000),travel1:number('travel1',0,10000),travel2:number('travel2',0,10000),drip:number('drip',0,36000),tiltPct:number('tiltPct',5,80),lowSide:number('lowSide',0,1),zones,order,drying:{enabled:+$('dryEnabled').checked,seconds:number('drySeconds',0,36000),staging:number('dryStaging',1,zones.length),x1:number('dryX1',0,10000),x2:number('dryX2',0,10000),z1:number('dryZ1',0,10000),z2:number('dryZ2',0,10000)}};}
async function applyProgram(){const d=collectProgram(),session=token();await request(`web program ${session} count ${d.zones.length}`);await request(`web program ${session} home ${d.home1} ${d.home2}`);await request(`web program ${session} travel ${d.travel1} ${d.travel2}`);await request(`web program ${session} recipe ${d.drip} ${d.tiltPct} ${d.lowSide}`);for(const z of d.zones)await request(`web zone ${session} ${z.n} ${z.x1} ${z.x2} ${z.z1} ${z.z2} ${z.dip} ${z.tilt} ${z.wait} ${z.hPct} ${z.vPct} ${z.enabled}`);const dry=d.drying;await request(`web program ${session} dry ${dry.enabled} ${dry.seconds} ${dry.staging} ${dry.x1} ${dry.x2} ${dry.z1} ${dry.z2}`);await request(`web program ${session} order ${d.order.join(' ')}`);formDirty=false;await request('web info');}
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function build(){
 names.forEach((d,i)=>{$('axes').insertAdjacentHTML('beforeend',`<div class="axis"><b>${labels[i]} <small>${d.toUpperCase()}</small></b><div class="value">—</div><div class="state">Нет данных</div><div class="hz">Выход —</div><div class="fault bad"></div></div>`);$('calCards').insertAdjacentHTML('beforeend',`<div class="card"><h3>${d.toUpperCase()} · ${labels[i]}</h3><div class="toolbar"><button data-calibrate="${d}" data-dir="fwd">Импульс FWD</button><button data-calibrate="${d}" data-dir="rev">Импульс REV</button></div><p class="result">Нужны два измерения</p></div>`);$('profiles').insertAdjacentHTML('beforeend',`<fieldset data-profile-card="${d}"><legend>${d.toUpperCase()}</legend>${[['manual','Ручная, %',10],['max','Максимальная, %',40],['slow','Медленная, %',10],['band','Зона замедления, мм',200],['tolerance','Допуск, мм',5]].map(([key,label,val])=>`<label>${label}<input data-key="${key}" type="number" value="${val}"></label>`).join('')}<button data-profile="${d}">Применить</button></fieldset>`);$('sensorSettings').insertAdjacentHTML('beforeend',`<fieldset data-sensor-card="${d}"><legend>${labels[i]}</legend><label>Смещение, мм<input data-offset type="number" min="-10000" max="10000" value="0"></label><label><input data-inverse type="checkbox"> Инверсия координаты</label><button data-sensor="${d}">Применить</button></fieldset>`);});
 for(const [target,mask,label] of [['h',3,'Горизонтальная пара'],['v',12,'Вертикальная пара'],['h1',1,'H1'],['h2',2,'H2'],['v1',4,'V1'],['v2',8,'V2']])$('jogCards').insertAdjacentHTML('beforeend',`<div class="card"><h3>${label}</h3><button class="jog" data-jog="${target}" data-mask="${mask}" data-dir="neg">−</button> <button class="jog" data-jog="${target}" data-mask="${mask}" data-dir="pos">+</button></div>`);
 for(const def of paramDefs){const row=document.createElement('tr');row.innerHTML=`<th>${def[0]}</th><td>${def[1]}</td>`+names.map(d=>`<td data-param="${def[0]}" data-drive="${d}"><div class="paramCell"><input type="number" step="${1/def[2]}" min="${def[3]}" max="${def[4]}" ${def[5]===false?'disabled':''}>${def[5]===false?'':`<button data-write-param title="Записать и проверить">✓</button>`}</div><span class="raw">Не прочитано</span></td>`).join('');$('params').appendChild(row);}
}
build();
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));}));
$('connect').addEventListener('click',connect);$('disconnect').addEventListener('click',disconnect);$('stop').addEventListener('click',stop);$('external').addEventListener('change',render);
$('arm').addEventListener('click',()=>action(async()=>{if(!$('external').checked)throw Error('Подтвердите готовность аппаратной защиты');await request(`web arm ${controller.session}`);note('Управление разрешено для текущего подключения');}));
$('clearSafety').addEventListener('click',()=>action(()=>request(`web clear ${controller.session}`)));
document.querySelectorAll('[data-jog]').forEach(b=>{b.addEventListener('pointerdown',e=>beginJog(b,e));for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,releaseJog);b.addEventListener('contextmenu',e=>e.preventDefault());});
document.querySelectorAll('[data-calibrate]').forEach(b=>b.addEventListener('click',()=>action(()=>request(`web calibrate ${token()} ${b.dataset.calibrate} ${b.dataset.dir} ${number('calPct',5,20)} ${number('calMs',500,3000)}`))));
$('forget').addEventListener('click',()=>action(()=>request(`web forget ${token()}`)));
for(const [id,cmd] of [['home','home'],['pause','pause'],['resume','resume'],['next','next']])$(id).addEventListener('click',()=>action(()=>request(`web ${cmd} ${token()}`)));
for(const [id,mode] of [['startAuto','auto'],['startSteps','steps']])$(id).addEventListener('click',()=>action(()=>request(`web start ${token()} ${mode}`)));
$('readParams').addEventListener('click',()=>action(readParameters));document.querySelectorAll('[data-write-param]').forEach(b=>b.addEventListener('click',()=>action(()=>writeParameter(b))));
$('loadProgram').addEventListener('click',()=>action(async()=>{await request(`web program ${token()} slot ${number('slot',1,4)}`);await request('web info');}));$('refreshProgram').addEventListener('click',()=>action(()=>request('web info')));
$('saveProgram').addEventListener('click',()=>action(async()=>{await applyProgram();await request(`web program ${token()} save`);note('Программа сохранена в Mega');}));$('applyProgram').addEventListener('click',()=>action(applyProgram));
document.querySelectorAll('[data-capture]').forEach(b=>b.addEventListener('click',()=>action(async()=>{await request(`web program ${token()} capture ${b.dataset.capture}`);await request('web info');})));
$('testPlan').addEventListener('click',()=>action(async()=>{await request(`web testplan ${token()} ${number('testDx',0,500)} ${number('testDz',0,500)} ${number('testWait',0,60)}`);await request('web info');note('Тестовая программа подготовлена. Проверьте координаты перед запуском.');}));
$('addZone').addEventListener('click',()=>{try{if(draft.zones.length>=10)throw Error('Максимум 10 зон');const current=collectProgram();draft={...current,order:[...current.order,current.zones.length+1],zones:[...current.zones,{enabled:1,x1:current.home1,x2:current.home2,z1:current.travel1,z2:current.travel2,dip:2,tilt:0,wait:0,hPct:10,vPct:10}]};formDirty=false;renderZones();dirty();}catch(e){note(e.message,true);}});
$('removeZone').addEventListener('click',()=>{try{const current=collectProgram();if(current.zones.length<=1)throw Error('В программе должна остаться хотя бы одна зона');current.zones.pop();current.order=current.order.filter(n=>n<=current.zones.length);draft=current;formDirty=false;renderZones();$('order').value=current.order.join(' ');dirty();}catch(e){note(e.message,true);}});
for(const id of ['home1','home2','travel1','travel2','drip','tiltPct','lowSide','order','dryEnabled','drySeconds','dryStaging','dryX1','dryX2','dryZ1','dryZ2'])$(id).addEventListener('change',dirty);
$('captureDry').addEventListener('click',()=>{if(axes.some(a=>!a||Number(a.age)>1200)){note('Нужны свежие координаты',true);return;}for(const [i,id] of ['dryX1','dryX2','dryZ1','dryZ2'].entries())$(id).value=axes[i].mm;dirty();});
$('exportProgram').addEventListener('click',()=>{try{download('telfer-program.json',JSON.stringify(collectProgram(),null,2),'application/json');}catch(e){note(e.message,true);}});
$('importProgram').addEventListener('change',async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(!Array.isArray(d.zones)||d.zones.length<1||d.zones.length>10)throw Error('Неверный формат программы');draft=d;renderProgramBase();formDirty=false;renderZones();$('order').value=(d.order||d.zones.map((_,i)=>i+1)).join(' ');collectProgram();dirty();note('Импортировано в форму. Примените для передачи в Mega.');}catch(e){note(e.message,true);}});
document.querySelectorAll('[data-profile]').forEach(b=>b.addEventListener('click',()=>action(async()=>{const card=b.closest('[data-profile-card]'),values=[...card.querySelectorAll('input')].map((x,i)=>integer(x.value,i<3?5:i===3?0:1,i<3?80:i===3?3000:100));await request(`web profile ${token()} ${b.dataset.profile} ${values.join(' ')}`);card.dataset.dirty='0';})));$('saveSettings').addEventListener('click',()=>action(()=>request(`web settings-save ${token()}`)));
document.querySelectorAll('[data-sensor]').forEach(b=>b.addEventListener('click',()=>action(async()=>{const card=b.closest('[data-sensor-card]');await request(`web sensor ${token()} ${b.dataset.sensor} ${+card.querySelector('[data-inverse]').checked} ${integer(card.querySelector('[data-offset]').value,-10000,10000)}`);card.dataset.dirty='0';await request('web info');})));
document.querySelectorAll('[data-profile-card] input,[data-sensor-card] input').forEach(input=>input.addEventListener('change',()=>{input.closest('fieldset').dataset.dirty='1';}));
$('saveLog').addEventListener('click',()=>download(`telfer-step9k-${new Date().toISOString().replace(/[:.]/g,'-')}.txt`,logLines.join('\n')));
window.addEventListener('blur',()=>{if(jog)releaseJog();});window.addEventListener('pagehide',()=>{if(connected())stop();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&connected())stop();});window.addEventListener('keydown',e=>{if(e.code==='Escape'&&connected())stop();});
setInterval(()=>{if(writer&&reading&&!supported&&Date.now()-lastHandshake>1000){lastHandshake=Date.now();write('service info').catch(()=>{});}if(armed()&&[...requests.values()].every(r=>r.response==='@WEB_PARAM '))write(`web ping ${controller.session}`).catch(()=>{});if(controller.armed==='1'&&Date.now()-lastRx>2200){note('Связь с Mega потеряна. Контроллер останавливает движение по таймеру.',true);controller.armed='0';releaseJog();}render();},250);
render();
